create table public.sender_bindings (
  id bigint generated by default as identity not null,
  receiver_mac text not null,
  sender_mac text not null,
  passcode text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint sender_bindings_pkey primary key (id)
) TABLESPACE pg_default;