create table public.sensor_data (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "Water_Level" bigint null,
  device_id text null,
  battery_percent integer null,
  solar_voltage numeric(4, 2) null,
  alert_message text null,
  constraint sensor_data_pkey primary key (id)
) TABLESPACE pg_default;